######################################################################
# Automatically generated by qmake (3.0) Sun Sep 17 22:31:34 2017
######################################################################

TEMPLATE = app
TARGET = birthday
INCLUDEPATH += .

# Input
SOURCES += main.cpp
